version: 3
metadata:
  category: Finance
  name: ItchySats
  version: "0.6.1"
  tagline: Peer-2-peer derivatives on Bitcoin
  description: >-
    ItchySats enables peer-2-peer CFD trading on Bitcoin using DLCs
    (discreet log contracts). No account needed, no trusted third-party - just you
    and your keys.


    This is beta software. We tested it on test- and mainnet, but there are no guarantees that it will always behave as expected.

    Please be mindful with how much money you trust the application with.

    CFDs trading is inherently risky, be sure to read up on it before using this application.


    That said: This is pretty awesome, go nuts!


    1. Fund the ItchySats wallet

    2. Open a position

    3. Monitor the price movement

    4. Profit


    Limitations of the mainnet beta:

    1. Minimum position quantity is $100, maximum $1000

  developers:
    ItchySats: https://itchysats.network
  dependencies:
    - electrs
  repo: https://github.com/itchysats/itchysats
  support: https://github.com/itchysats/itchysats/issues
  port: 7113
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  path: ""
  defaultUsername: itchysats
  deterministicPassword: true
  torOnly: false
  releaseNotes: >-
    This release fixes a minor UI bug for 0.6.0.

    Release 0.6.0 enables ETHUSD CFDs. You can now trade BTCUSD and ETHUSD using your Bitcoin.

    With release 0.6.0 support for the legacy network stack is dropped; versions prior to 0.5.4 are not supported anymore and have to upgrade to maintain compatibility.
