version: 3
metadata:
  category: Finance
  name: ItchySats
  version: "0.6.1"
  tagline: Peer-2-peer derivatives on Bitcoin
  description: >-
    ItchySats enables peer-2-peer CFD trading on Bitcoin using DLCs
    (discreet log contracts). No account needed, no trusted third-party - just you
    and your keys.


    This is beta software. We tested it on test- and mainnet, but there are no guarantees that it will always behave as expected.

    Please be mindful with how much money you trust the application with.

    CFDs trading is inherently risky, be sure to read up on it before using this application.


    That said: This is pretty awesome, go nuts!


    1. Fund the ItchySats wallet

    2. Open a position

    3. Monitor the price movement

    4. Profit


    Limitations of the mainnet beta:

    1. Minimum position quantity is $100, maximum $1000

  developers:
    ItchySats: https://itchysats.network
  dependencies:
    - electrs
  repo: https://github.com/itchysats/itchysats
  support: https://github.com/itchysats/itchysats/issues
  port: 7113
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  path: ""
  defaultUsername: itchysats
  defaultPassword: $APP_SEED
  torOnly: false
containers:
  - name: itchysats
    image: ghcr.io/itchysats/itchysats/taker:0.6.1@sha256:5ad0baea350bee41b6e828030ff37f7bb61359d381c7afd15f874ee2bf9d6c62
    restart: on-failure
    user: 1000:1000
    port: 8000
    stop_grace_period: 1m
    volumes:
      - data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $BITCOIN_NETWORK
      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT
    environment:
      - ITCHYSATS_ENV=citadel
      - APP_PASSWORD:=${APP_SEED}
